# -*- coding: utf-8 -*-
"""day 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PrYBTGWU1hISNj6gKIqAPq3LvRK2dEup

assignment 2
"""

a=int(input());
if a<=1000:
  print("safe to land")
elif a>1000 and a<5000:
  print("bring down to 1000")
else:
    print("turn around")