# -*- coding: utf-8 -*-
"""1st class.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K6IoDorPgSf-h1zLxG4HcgZfV9fjHlxf

assignment 1 ,day 2
"""

lst = [1,2,3,'a','b']
lst.append("3")
lst

lst = [1,2,3,4,'vin','cin']
lst.insert(3,'k')
lst

lst = [1,3,6,'v']
lst.pop(1)

lst = [1,3,8,9,'h','i']
lst.reverse()
lst

lst =[9,8,7,6,6,6,'b','c']
lst.count(6)

"""assignment 2,day 2"""

dit = {"key":100,"key1":200}
dit.get("key")

data = {"name":"vinil","age":19}
data.get("name")

data = {"name":"vinil","age":19}
data.items()

data = {"name":"vinil","age":19}
data.pop("age")

data = {"name":"vinil","age":19}
data.keys()

data = {"name":"vinil","age":19}

data.clear()